Description: Lambda function
Parameters:
  LambdaFunctionName:
    Description: FunctionName
    Type: String
    Default: LambdaSNSFunction
Resources:
  LambdaFunc:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Role: !ImportValue RoleArn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            print("hello world")
            for record in event['Records']:
              process_message(record)
          print("done")
          def process_message(record):
            try:
              message = record['Sns']['Message']
              print(f"Processed message {message}")
              # TODO; Process your record here
         
            except Exception as e:
              print("An error occurred")
              raise e
 
      Runtime: "python3.12"
      Handler: "index.lambda_handler"
Outputs:
  LambdaARN:
    Description: Lambda function ARN
    Value: !GetAtt LambdaFunc.Arn
    Export:
      Name: LambdaFuncArn