Resources:
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn:  !ImportValue SNSTopicArn
      FunctionName: !ImportValue LambdaFuncArn